"""empty message

Revision ID: 0194e56018fd
Revises: e40d49e982da
Create Date: 2020-05-01 22:26:40.416065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0194e56018fd'
down_revision = 'e40d49e982da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eats')
    op.add_column('Recipe', sa.Column('personId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Recipe', 'people', ['personId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Recipe', type_='foreignkey')
    op.drop_column('Recipe', 'personId')
    op.create_table('eats',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('recipeId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['people.id'], name='eats_ibfk_1'),
    sa.ForeignKeyConstraint(['recipeId'], ['Recipe.recipeId'], name='eats_ibfk_2'),
    sa.PrimaryKeyConstraint('id', 'recipeId'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
