"""empty message

Revision ID: 0d8940753485
Revises: e2e25fae0225
Create Date: 2020-04-07 05:35:34.129183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d8940753485'
down_revision = 'e2e25fae0225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('name', sa.String(length=255), nullable=False))
    op.drop_column('people', 'lastName')
    op.drop_column('people', 'firstName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('firstName', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('people', sa.Column('lastName', mysql.VARCHAR(length=225), nullable=False))
    op.drop_column('people', 'name')
    # ### end Alembic commands ###
