"""empty message

Revision ID: 11f70e179331
Revises: 553915fdbc4a
Create Date: 2020-04-07 06:13:12.021902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11f70e179331'
down_revision = '553915fdbc4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('name', sa.String(length=255), nullable=False))
    op.drop_column('people', 'firstName')
    op.drop_column('people', 'lastName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('lastName', mysql.VARCHAR(length=225), nullable=False))
    op.add_column('people', sa.Column('firstName', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('people', 'name')
    # ### end Alembic commands ###
