"""empty message

Revision ID: 366e679413ce
Revises: 7159722e0418
Create Date: 2020-04-09 20:53:23.102938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366e679413ce'
down_revision = '7159722e0418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Recipe',
    sa.Column('recipeId', sa.Integer(), nullable=False),
    sa.Column('recipeName', sa.String(length=255), nullable=False),
    sa.Column('protein', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('recipeId')
    )
    op.create_table('eats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipeId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['recipeId'], ['Recipe.recipeId'], ),
    sa.PrimaryKeyConstraint('id', 'recipeId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eats')
    op.drop_table('Recipe')
    # ### end Alembic commands ###
