"""empty message

Revision ID: 4684ee1b7f70
Revises: 11f70e179331
Create Date: 2020-04-07 06:15:24.728483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4684ee1b7f70'
down_revision = '11f70e179331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('name', sa.String(length=255), nullable=False))
    op.drop_column('people', 'firstName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('firstName', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('people', 'name')
    # ### end Alembic commands ###
