"""empty message

Revision ID: 66f05a66792b
Revises: 366e679413ce
Create Date: 2020-04-09 22:25:11.884191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f05a66792b'
down_revision = '366e679413ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CompletedWorkout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personId', sa.Integer(), nullable=True),
    sa.Column('workoutId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personId'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CompletedWorkout')
    # ### end Alembic commands ###
