"""empty message

Revision ID: 7159722e0418
Revises: 41ada4513661
Create Date: 2020-04-07 06:35:19.235425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7159722e0418'
down_revision = '41ada4513661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('firstName', sa.String(length=255), nullable=False))
    op.add_column('people', sa.Column('lastName', sa.String(length=255), nullable=False))
    op.drop_column('people', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('people', 'lastName')
    op.drop_column('people', 'firstName')
    # ### end Alembic commands ###
