"""people table

Revision ID: cd94ae07eb15
Revises: 8091de7197b2
Create Date: 2020-04-06 15:55:37.025524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd94ae07eb15'
down_revision = '8091de7197b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('publicId', table_name='people')
    op.drop_column('people', 'publicId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('publicId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('publicId', 'people', ['publicId'], unique=True)
    # ### end Alembic commands ###
